version: '3.5'

services:
  db:
    image: 'postgres:11-alpine'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    env_file:
      - config/docker.env

  app:
    image: kreasidev:0.4.8
    ports:
      - '80:4000'
    env_file:
      - config/docker.env
    depends_on:
      - db
volumes:
  pgdata:
